### ISSUE TITLE
Problem with connection between CakePHP and MongoDB

### ISSUE THREAD

**Issue by punit1108** [ichikaway/cakephp-mongodb#129]
When i run my **localhost/cake/**, it shows the following error : 

![image](https://cloud.githubusercontent.com/assets/7887355/6996623/bc40244e-dbb0-11e4-9d10-8c116ebcaf5f.png)

i have searched for this everywhere, and i am new to Cakephp-MongoDB. Please guide accordingly.

**Comment by imkven** [comment]
You need install MongoDB driver for PHP.

http://docs.mongodb.org/ecosystem/drivers/php/
